name: CD

on: 
  workflow_call:
    inputs: 
      latestSHA:
        required: true
        type: string



jobs:
  publish_npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Initialize repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.latestSHA }}

      - name: Prepare Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Prepare package
        run: npm ci
      
      - name: Publish package 
        run: npm publish 
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}