name: Node CI

on: [push]

jobs:
  test_and_bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Initialize repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          CI: true

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v9.1.0

      - name: Get new git commit SHA
        id: committer
        run: |
          SHA=$(git rev-parse HEAD)
          echo "::set-output name=commitid::$SHA"

  call_cicd_workflow:
    needs: test_and_bump
    name: Call the CD workflow
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    with:
      latestSHA: ${{ test_and_bump.committer.outputs.commitid }}
